### ISSUE TITLE
Change setup_requires to install_requires

### ISSUE THREAD

**Issue by jakirkham** [em-MRCZ/python-mrcz#11]
If `numpy` and `futures` are not needed to build the package (guessing they are not), they should not be listed under `setup_requires`. Instead they (`numpy` and `futures`) should be listed under `install_requires`. By adding them under `install_requires`, it means that the package can be built and installed without them, but they (`numpy` and `futures`) should be satisfied at install time so the user has access to them.

ref: https://github.com/em-MRCZ/python-mrcz/blob/v0.3.6/setup.py#L87

**Comment by robbmcleod** [comment]
Looks to be fixed in e6403e537a71d46d98984328c9846904d4ac5543, closing
